Fixed test
mafintosh/webrtc-swarm pull request #20
Opened 2016-09-06 21:33 UTC by lukeburns

Fixes https://github.com/mafintosh/webrtc-swarm/issues/19

2016-09-06 22:08 UTC, lukeburns commented
Added a test for > 2 peers in response to https://github.com/mafintosh/webrtc-swarm/issues/18

2017-09-28 15:13 UTC, perguth requested changes

2017-09-28 15:13 UTC, perguth commented on test.js
> +  var key = randomHex('64')
In the signalhub documentation it's called 'appName'. Maybe stick to that nomenclature!?

2017-09-28 15:13 UTC, perguth commented on test.js
> +tape('three peers connect and close', function (t) {
I am not in favour of using `t.ok(1, ...)`. ~~Also if this test fails it will throw a `not ok 1 plan != count` error message instead of something usable.~~ (it seems we can't avoid that - but `t.pass(...)` looks better, imho)

2017-09-28 15:13 UTC, perguth commented on test.js
> +tape('three peers connect and close', function (t) {
Maybe use this `Fixed test` pull request *just* to fix the test and not introduce a new one? (Maybe another pull for the new test?)

2017-10-06 00:09 UTC, pguth commented
@lukeburns what do you think about https://github.com/mafintosh/webrtc-swarm/pull/30? Would that be a benefit for the current codebase?

2017-11-01 22:03 UTC, perguth commented
Closing this in favour of https://github.com/mafintosh/webrtc-swarm/pull/30. But thank you very much nonetheless!

2017-11-01 22:03 UTC, closed without merging